# Generated by Django 4.0.6 on 2022-09-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_app', '0002_rename_role_role_role_user_remove_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
