# Generated by Django 4.0.6 on 2022-09-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
