# Generated by Django 4.0.6 on 2022-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
